name: Sync

on:
  push:
    branches: [master]
    paths: ['src/**', 'test/**']

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Merge master to examples
        uses: devmasx/merge-branch@v1.3.1
        with:
          type: now
          target_branch: examples
          github_token: ${{ github.token }}
